### ISSUE TITLE
differentiate NA/UNKNOWN/INVALID by default?

### ISSUE THREAD

**Issue by wchristian** [eserte/cpan-testers-matrix#16]
Right now those three use the same color by default, but in my development of OpenGL.pm, a module that has a lot of fragility in the makefile, being able to use signaling beyond FAIL/PASS is important. Could we change the default settings to differentiate the three by using different colors?

A temporary fix i'm using right now is to use UserCSS to apply the following:

`.action_UNKNOWN { background:coral !important; }
.action_INVALID { background:tomato !important; }`

With these results:

![image](https://cloud.githubusercontent.com/assets/175467/19108710/20c7d26c-8af2-11e6-9936-1608cdae6767.png)

**Comment by eserte** [comment]
I think it's a valid point. I implemented different coloring for NA/UNKNOWN/INVALID on the beta site. You can see your module here:
http://beta-matrix.cpantesters.org/?dist=Acme-MITHALDU-BleedingOpenGL+0.67049

Note that the coloring is slightly different then in your CSS --- UNKNOWN stays orange, while NA is coral now. INVALID is not an official state anyway (it can only be set through a configuration file within the cpantestersmatrix system), so it gets a completely different rendering. Here's a rare view which has INVALID entries:
http://beta-matrix.cpantesters.org/?dist=Tk+804.030

**Comment by wchristian** [comment]
I don't particularly care which way the coloring goes, and i'm glad you're adding differentiation. :D

Separating INVALID out like that seems useful as well.

Thanks for your effort. If you don't need this one for tracking purposes, i think it can be closed. :)

**Comment by eserte** [comment]
The change is now also on the non-beta site.

**Comment by wchristian** [comment]
That is great. Thanks a lot!
