### ISSUE TITLE
Time travel: http://matrix.cpantesters.org reports future time

### ISSUE THREAD

**Issue by rwfranks** [eserte/cpan-testers-matrix#18]
Looking at test report matrix for Net::DNS 1.18, I was astonished to see the last report shown 7 hours into the future.

First report: 2018-09-21 15:52 BST (31 days ago)
Last report: 2018-10-23 01:26 BST
  PASS: 1211
Number of tested configurations: 215

Current time is:  Mon 22 Oct 18:18:38 BST 2018

The fault also appears in the table under the "ALL" link:

Result | Id | OS vers | archname | Perl version | OS | Tester | Date | Comment
-- | -- | -- | -- | -- | -- | -- | -- | --
99435019 | 2.11 | i86pc-solaris | 5.29.1 | solaris | STRO | 2018-10-23 00:26 |  
99434624 | 11.2-release-p4 | amd64-freebsd-thread-multi | 5.29.5 | freebsd | Carlos Guevara | 2018-10-22 15:57 | 

AFAICT this is not the only example.

**Comment by rwfranks** [comment]
The red exclamation mark idea would be good interim measure.
Longer term, better to timestamp reports when added to database, or at the very least, discard submissions with times too far removed from the truth.

Unreliable timestamps might also offer an explanation of the the oldest page request being stuck in the works since February!


Status | EXCELLENT
-- | --
Most recent report | 2018-10-23 15:56:00 (99462323)
Time of oldest page request | 2018-02-03 20:08:02 EDT
Total page requests | 4345
Total unique page requests | 1029

**Comment by eserte** [comment]
Thinking again about it, the red exclamation feature would be of limited value. The matrix system itself has no "memory" --- it fetches everything from the main cpantesters site on demand (plus it's doing some dumb caching) and that's it. So once the report date is reached in reality the exclamation mark would not be shown again (but the information that the report date was wrong would still be useful).

If the CPAN Testers DB had two timestamps, the user's report generation date and the delivery date into the CPAN Testers DB, and the latter timestamp would be controlled by the CPAN Testers API, then the mismatch could be reliably determined. Maybe the CPAN Testers DB already has this data, but does not propagate it into the generated JSON files. I would suggest to move the discussion to https://github.com/cpan-testers/cpantesters-project/issues

**Comment by rwfranks** [comment]
I agree, this appears to be a one-off curiosity, with no lasting
significance.
