### ISSUE TITLE
Not working for dists ending in -v1

### ISSUE THREAD

**Issue by abraxxa** [eserte/cpan-testers-matrix#19]
I've released Net::Cisco::FMC::v1 to CPAN and checked CPANTesters but the URL http://matrix.cpantesters.org/?dist=Net-Cisco-FMC-v1 gives an error page which reads:

> An error was encountered:
> Distribution results for \<Net-Cisco-FMC\> at <http://www.cpantesters.org/show/Net-Cisco-FMC.json> not found.

Passing the version too works: http://matrix.cpantesters.org/?dist=Net-Cisco-FMC-v1%200.001001

It looks like if the -v1 is cut off.

**Comment by eserte** [comment]
This looks like a variation of the problem where the heuristics has to decide whether it's a distname or a combined distname+version. Other problematic distributions are POSIX-1003 or Acme-6502, and these have now a special handling. I'll add also Net-Cisco-FMC-v1 to the special handling list, but it would be better to have a generic solution...

**Comment by eserte** [comment]
I deployed the workaround to matrix & fast-matrix.

**Comment by abraxxa** [comment]
Thanks for the quick fix!
Why is -v\d interpreted as dist version number at all when a space inbetween seems to be the spec?

**Comment by eserte** [comment]
Both is accepted, separating distname and version with a space or with a dash. (Which was probably not a wise decision then...)
