### ISSUE TITLE
Testers-matrix does not fail on non-satisfied strict pre-req

### ISSUE THREAD

**Issue by cub-uanic** [eserte/cpan-testers-matrix#21]
Please check https://github.com/perlancar/perl-Perinci-Sub-Complete/issues/1

The current Perinci::Sub::Complete (0.943) requires Complete::Getopt::Long 0.479, which doesn't exists (latest current version is 0.478).
See https://metacpan.org/source/PERLANCAR/Perinci-Sub-Complete-0.943/Makefile.PL and https://metacpan.org/release/Complete-Getopt-Long.
As a result, the Perinci::Sub::Complete can't be installed in fresh environment (for example, new Perl install via plenv).
However, testers matrix is almost green: http://matrix.cpantesters.org/?dist=Perinci-Sub-Complete+0.943

And according to logs, the strict requirement of 0.479 was ignored and 0.478 was used, for example:
http://www.cpantesters.org/cpan/report/b87d2228-b808-11ea-a319-193bcccccfd6
http://www.cpantesters.org/cpan/report/8a7d103e-b805-11ea-9066-e374b0ba08e8

I'm not sure if this bug in cpan-testers-matrix or somewhere else, will be glad if you confirm or point me to the right direction.

**Comment by eserte** [comment]
The CPAN Testers Matrix is definitely the wrong place to report the problem, as it's just a visualization tool. So I'll close this issue.

To give some insight what's happening here: unlike typical CI systems like travis-ci or github actions the smoker systems generating the reports for the CPAN Testers system do not necessarily run on empty environments. The systems may not be dedicated smokers at all, but for example user's perl installations used for their everyday's work. For the smoker systems there are several types of setups: systems which only test, but never install, systems which install some of previously tested distributions, and systems which install everything. The latter type could be responsible for the PASS reports you saw: in a previous run Complete::Getopt::Long 0.478 was tested and installed.

The responsibility to decide if a test run is successful is built into CPAN::Reporter (and compatible modules for non-CPAN.pm setups). It reports the status of the last phase (configure, build, test). As the test was successful (despite of the too low version of Complete::Getopt::Long), the result was rightfully "test PASS". For other systems, where Complete::Getopt::Long was not yet installed and thus the test suite fails, the result was probably "test DISCARD" indicating a dependency problem --- but dependency problems are never reported to the CPAN Testers system.

**Comment by eserte** [comment]
Probably the best place to discuss such things is the cpan-testers-discuss mailing list, see https://lists.perl.org/list/cpan-testers-discuss.html
